### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by d4n3436** [d4n3436/Fergun#1]
# To-Do List

Here I will put all the improvements and changes that need to be made in future updates.

- [x] Prepare the bot for self-hosting.
  - [x] Move API tokens and other config from the database to a local config file.
  - [x] Make the reliability service optional.
  - [x] Use a database config file for remote database access.
  - [x] Use a Lavalink config file for remote Lavalink server access.
- [x] Rewrite `code` to  get the line number of a specified command from the repository.
- [ ] Sharding support.
- [ ] Rewrite the music module/service.
- [ ] Rewrite the AI Dungeon adventure creator (or maybe the entire module).
- [ ] Use constant websocket connections for the requests to the AI Dungeon API.
  - [ ] Use a GraphQL library that handles the requests, responses, and the connections.
- [x] Find an alternative or create a wrapper for the new free Google Translate/TTS method (the current method no longer works).
- [ ] Improve the performance and reduce the memory usage of `eval`.
- [ ] An `update` command that updates the bot, downloading the code from the repo, building the bot, and restarting itself.
  - [ ] A way to update the module assemblies without restarting the bot.

**Comment by d4n3436** [comment]
Moved to the [wiki](https://github.com/d4n3436/Fergun/wiki/To-Do-list).
